[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'cd ..',
  'npm ci',
  'cd server',
  'npm ci'
]

[phases.build]
cmds = [
  'cd ..',
  'npm run build',
  'cd server',
  'echo "Build complete"'
]

[start]
cmd = 'NODE_ENV=production node server.js'

